apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gql-gateway-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /gql-gateway
        backend:
          serviceName: gql-gateway
          servicePort: 80
